### ISSUE TITLE
Themes not applying at all.

### ISSUE THREAD

**Issue by Soulreaver90** [catppuccin/stable-diffusion-webui#25] opened 2023-03-27 00:03 UTC
I've installed the extensions but the UI isn't changing at all. I've reloaded and tried multiple times and various accents, but it remains at the default, dark theme or not. I've unloaded all my extensions and tried again with no success. I am running on commit a9fed7c, which is before the 3.23 gradio changes.

**Comment by Kettukaa** [comment] 2023-04-06 02:41
I see, so the issue is that there are now two versions of the theme (original and post gradio update). I guess the solution is to have both themes exist and just check for the gradio version? I can work on this soon. Thanks for bringing this to my attention.

**Comment by Kettukaa** [comment] 2023-04-06 04:20
The most recent commit should fix the issue for legacy gradio versions, please let me know if it persists. If it doesn't work, then change your theme in the settings, save, then press the reload button.

**Comment by Kettukaa** [comment] 2023-04-06 18:24
Most recent commit just fixed the accent color not being applied on legacy gradio versions. I believe this issue is solved so I'll be closing this. Please feel free to reopen this issue, or start a new issue, if there is a problem.

**Closed as completed by Kettukaa** 2023-04-06 18:24 UTC
